### ISSUE TITLE
Conflict dependency with gossy/php-code-profiles

### ISSUE THREAD

**Issue by AlexAzartsev** [phpowermove/php-code-formatter#25] opened 2020-04-02 08:25 UTC
This package require 
"symfony/yaml" : "~2|^3|^4",
"gossi/php-code-profiles" : "dev-master"

but gossy/php-code-profiles already require
symfony/yaml: ^5.0
This produce conflict and composer update stop working, please update dependencies of php-code-formatter and php-code-generator

**Comment by gossi** [comment] 2020-04-08 19:27
yeah, there are a couple of changes on the way. Most prominent is that phootwork was released in v2 which raised a lot of version of its dependencies. Same will happen for more. 

All kudos to @cristianoc72 who is the main driver here.

**Comment by cristianoc72** [comment] 2020-04-09 08:16
The problem is caused by the last two commits in `gossi/php-code-profiles` library.

I'm working on the improvement of `php-code-formatter` but it's harder and more time-expensive then I thought. By now, we could solve this issue via the following:

1.  draft the `0.1` version of `gossi/php-code-profiles` tagging the `a5ed51981ca2d0a361bc17d947fba92e4ad6013c`, which is the commit BEFORE my changes.
2.  require this version in the current `composer.json` of `php-code-formatter`.

@gossi wdyt?

**Comment by gossi** [comment] 2020-04-10 07:43
A dependency to a specific commit usually disallows caching on the composer consumer side. With that, tagging the sha you mentioned seems ok to me.

**Closed** 2022-07-02 16:06 UTC
